# file: _config.yml
theme: jekyll-theme-minimal
title: CJ's homepage
description: "Stay tuned for my project updates! Next on the list: Coffee rating app!"
github_url: https://github.com/cjwiesenfeld
