# file: _config.yml
theme: jekyll-theme-minimal
title: CJ's homepage
description: "Check out a couple past projects! Next on the list: Coffee rating app!"
github_url: https://github.com/cjwiesenfeld/personal_work/
